# Generated by Django 3.2.8 on 2021-10-30 00:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('sis', '0002_class_grade'),
        ('users', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='customuser',
            name='classes',
            field=models.ManyToManyField(to='sis.Class'),
        ),
        migrations.AddField(
            model_name='customuser',
            name='grades',
            field=models.ManyToManyField(to='sis.Grade'),
        ),
    ]
