# Generated by Django 3.2.8 on 2021-10-30 00:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('sis', '0002_class_grade'),
        ('users', '0002_auto_20211029_2052'),
    ]

    operations = [
        migrations.AlterField(
            model_name='customuser',
            name='classes',
            field=models.ManyToManyField(blank=True, to='sis.Class'),
        ),
        migrations.AlterField(
            model_name='customuser',
            name='grades',
            field=models.ManyToManyField(blank=True, to='sis.Grade'),
        ),
        migrations.AlterField(
            model_name='customuser',
            name='school',
            field=models.ManyToManyField(blank=True, to='sis.School'),
        ),
    ]
