# Generated by Django 3.2.8 on 2021-10-30 01:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0004_remove_customuser_grades'),
        ('sis', '0002_class_grade'),
    ]

    operations = [
        migrations.AddField(
            model_name='class',
            name='grade',
            field=models.FloatField(default=100.0),
            preserve_default=False,
        ),
        migrations.DeleteModel(
            name='Grade',
        ),
    ]
