# Generated by Django 3.2.8 on 2021-11-01 23:22

from django.db import migrations, models
import uuid


class Migration(migrations.Migration):

    dependencies = [
        ('sis', '0006_profile_user'),
    ]

    operations = [
        migrations.AddField(
            model_name='school',
            name='staff_code',
            field=models.UUIDField(default=uuid.uuid4, editable=False),
        ),
        migrations.AddField(
            model_name='school',
            name='student_code',
            field=models.CharField(default='76169804', max_length=5, unique=True),
        ),
    ]
