# Generated by Django 3.2.9 on 2021-11-27 03:03

import django.core.validators
from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('sis', '0007_auto_20211101_1922'),
    ]

    operations = [
        migrations.CreateModel(
            name='Category',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=150)),
                ('weight', models.FloatField(validators=[django.core.validators.MinValueValidator(0.0), django.core.validators.MaxValueValidator(100.0)])),
                ('value', models.FloatField(validators=[django.core.validators.MinValueValidator(0.0), django.core.validators.MaxValueValidator(100.0)])),
            ],
        ),
        migrations.CreateModel(
            name='Entry',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=150)),
                ('date', models.DateTimeField(default=django.utils.timezone.now)),
                ('grade', models.FloatField(validators=[django.core.validators.MinValueValidator(0.0), django.core.validators.MaxValueValidator(100.0)])),
            ],
        ),
        migrations.AlterField(
            model_name='school',
            name='student_code',
            field=models.CharField(default='7CFC78B1', max_length=5, unique=True),
        ),
        migrations.AddConstraint(
            model_name='entry',
            constraint=models.CheckConstraint(check=models.Q(('grade__gte', 0.0), ('grade__lte', 100.0)), name='grade_range'),
        ),
        migrations.AddConstraint(
            model_name='category',
            constraint=models.CheckConstraint(check=models.Q(('weight__gte', 0.0), ('weight__lte', 100.0)), name='weight_range'),
        ),
        migrations.AddConstraint(
            model_name='category',
            constraint=models.CheckConstraint(check=models.Q(('value__gte', 0.0), ('value__lte', 100.0)), name='value_range'),
        ),
        migrations.AddField(
            model_name='class',
            name='categories',
            field=models.ManyToManyField(related_name='categories', to='sis.Category'),
        ),
    ]
