# Generated by Django 3.2.9 on 2022-01-05 17:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('sis', '0009_auto_20220105_1258'),
    ]

    operations = [
        migrations.AddField(
            model_name='class',
            name='code',
            field=models.CharField(default='41EDA45F', editable=False, max_length=5, unique=True),
        ),
        migrations.AlterField(
            model_name='school',
            name='student_code',
            field=models.CharField(default='D8E63F25', editable=False, max_length=5, unique=True),
        ),
    ]
