# Generated by Django 3.2.9 on 2022-01-07 23:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('sis', '0011_auto_20220107_1740'),
    ]

    operations = [
        migrations.AlterField(
            model_name='class',
            name='categories',
            field=models.ManyToManyField(blank=True, related_name='categories', to='sis.Category'),
        ),
        migrations.AlterField(
            model_name='class',
            name='code',
            field=models.CharField(default='8D12BF1D', editable=False, max_length=5, unique=True),
        ),
        migrations.AlterField(
            model_name='school',
            name='student_code',
            field=models.CharField(default='BDB24B94', editable=False, max_length=5, unique=True),
        ),
    ]
